ml /D mdl=3 /Cx prog1-1.asm 
ml /D mdl=3 /Cx prog1-2.asm 
ml /D mdl=3 /Cx prog1-3.asm 
ml /D mdl=3 /Cx prog1-4.asm 
ml /D mdl=3 /Cx prog1-5.asm 
ml /D mdl=3 /Cx prog1-6.asm 
ml /D mdl=3 /Cx prog1-7.asm 
ml /D mdl=3 /Cx prog1-8.asm 
ml /D mdl=3 /Cx prog1-9.asm 
ml /D mdl=3 /Cx prog1-10.asm
ml /D mdl=3 /Cx prog2-1.asm   /link tab60l.lib
ml /D mdl=3 /Cx prog2-2.asm   /link tab60l.lib
ml /D mdl=3 /Cx prog3-1.asm   /link tab60l.lib
ml /D mdl=3 /Cx prog4-1.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-2.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-3.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-4.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-5.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-6.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-7.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-8.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-9.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-10.asm  /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-11.asm  /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-12.asm  /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog4-13.asm  /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog5-1.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog6-1.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog7-1.asm   /link /CP:32768 tab60l.lib
ml /D mdl=3 /Cx prog7-2.asm   /link /CP:32768 tab60l.lib

           
 
