///////////////////////////////////////
//
// ascii.h
//
// ASCII define header file
//
///////////////////////////////////////

#define   aNUL   0       //      null \0 delimeter
#define   aSOH   1       //  ^A - start of heading
#define   aSTX   2       //  ^B - start of text
#define   aETX   3       //  ^C - end of text
#define   aEOT   4       //  ^D - end of transmission
#define   aENQ   5       //  ^E - inquiry
#define   aACK   6       //  ^F - affirm acknowledgement
#define   aBEL   7       //  ^G - audible bell
#define   aBS    8       //  ^H - backspace
#define   aTAB   9       //  ^I - horizontal tab
#define   aLF    10      //  ^J - line feed
#define   aVT    11      //  ^K - vertical tab
#define   aFF    12      //  ^L - form feed
#define   aCR    13      //  ^M - carriage return
#define   aSO    14      //  ^N - shift out
#define   aSI    15      //  ^O - shift in
#define   aDCE   16      //  ^P - data link escape
#define   aDC1   17      //  ^Q - device control 1
#define   aDC2   18      //  ^R - device control 2
#define   aDC3   19      //  ^S - device control 3
#define   aDC4   20      //  ^T - device control 4
#define   aNAK   21      //  ^U - neg acknowledge 
#define   aSYN   22      //  ^V - synchronous idle
#define   aETB   23      //  ^W - end of transmission
#define   aCAN   24      //  ^X - cancel
#define   aEM    25      //  ^Y - end of medium
#define   aSUB   26      //  ^Z - substitute
#define   aESC   27      //       escape
#define   aFS    28      //       file sererator 
#define   aGS    29      //       group seperator 
#define   aRS    30      //       record seperator 
#define   aUS    31      //       unlinked seperator 
#define   aSPC   32      //       space 

#define   aCODE     94   // character indicating printer command follows// 
#define   aHCR      aEOT //  Hard carriage return
#define   aCENTER   'C'  //  code to center line
#define   aDOUBLE   'D'  //  double strike toggle
#define   aEXPAND   'E'  //  emphasize toggle
#define   aSUPERS   'S'  //  superscript toggle
#define   aITALIC   'I'  //  italics toggle
#define   aBOLD     'B'  //  bold toggle
                         // 
#define   aTRUE     1    //  true
#define   aFALSE    0    //  false













