;--------------------------------------
;
; global6.inc
;
; public data for use in many routines
;


EXTERNDEF scrn_buf:Word
EXTERNDEF scrn_seg:Word
EXTERNDEF string_length:Word
EXTERNDEF token_value:Word
EXTERNDEF string_length:Word
EXTERNDEF return_value:Word
EXTERNDEF write_length:Word

EXTERNDEF cursor_start:Byte
EXTERNDEF cursor_end:Byte
EXTERNDEF cursor_row:Byte
EXTERNDEF cursor_column:Byte
EXTERNDEF cursor_visible:Byte
EXTERNDEF char_value:Byte
EXTERNDEF attribute_value:Byte


