copy prog1-1.asm  ..\fig\fig1-1.doc
copy prog1-2.asm  ..\fig\fig1-2.doc
copy prog1-3.asm  ..\fig\fig1-3.doc
copy prog1-4.asm  ..\fig\fig1-4.doc
copy prog1-5.asm  ..\fig\fig1-5.doc
copy prog1-6.asm  ..\fig\fig1-6.doc
copy prog1-7.asm  ..\fig\fig1-7.doc
copy prog1-8.asm  ..\fig\fig1-8.doc
copy prog1-9.asm  ..\fig\fig1-9.doc
copy proto6s.inc  ..\fig\fig1-10.doc
copy proto6l.inc  ..\fig\fig1-11.doc
copy prog1-10.asm ..\fig\fig1-12.doc

copy prog2-1.asm  ..\fig\fig2-1.doc
copy prog2-2.asm  ..\fig\fig2-2.doc
copy tab6.inc     ..\fig\fig2-3.doc
copy mac6.inc     ..\fig\fig2-4.doc
copy def6.inc     ..\fig\fig2-5.doc
copy global6.inc  ..\fig\fig2-6.doc
copy global6.asm  ..\fig\fig2-7.doc
copy mvcur.asm    ..\fig\fig2-8.doc
copy setcur.asm   ..\fig\fig2-9.doc
copy oncur.asm    ..\fig\fig2-10.doc
copy offcur.asm   ..\fig\fig2-11.doc
copy gtcur.asm    ..\fig\fig2-12.doc
copy restcur.asm  ..\fig\fig2-13.doc
copy clrscrn.asm  ..\fig\fig2-14.doc
copy bdwrite.asm  ..\fig\fig2-15.doc

copy prog3-1.asm  ..\fig\fig3-1.doc
copy mkattr.asm   ..\fig\fig3-2.doc
copy mktoken.asm  ..\fig\fig3-3.doc
copy vidinit.asm  ..\fig\fig3-4.doc
copy vdwrite.asm  ..\fig\fig3-5.doc
copy vdchar.asm   ..\fig\fig3-6.doc
copy vdattr.asm   ..\fig\fig3-7.doc
copy vdhrep.asm   ..\fig\fig3-8.doc
copy vdvrep.asm   ..\fig\fig3-9.doc
copy savescrn.asm ..\fig\fig3-10.doc
copy restscrn.asm ..\fig\fig3-11.doc
copy vrdchar.asm  ..\fig\fig3-12.doc

copy prog4-1.asm  ..\fig\fig4-1.doc
copy prog4-2.asm  ..\fig\fig4-2.doc
copy prog4-3.asm  ..\fig\fig4-3.doc
copy prog4-4.asm  ..\fig\fig4-4.doc
copy prog4-5.asm  ..\fig\fig4-5.doc
copy prog4-6.asm  ..\fig\fig4-6.doc
copy prog4-7.asm  ..\fig\fig4-7.doc
copy prog4-8.asm  ..\fig\fig4-8.doc
copy prog4-9.asm  ..\fig\fig4-9.doc
copy prog4-10.asm ..\fig\fig4-10.doc
copy prog4-11.asm ..\fig\fig4-11.doc
copy prog4-12.asm ..\fig\fig4-12.doc
copy prog4-13.asm ..\fig\fig4-13.doc
copy memset.asm   ..\fig\fig4-14.doc
copy strlen.asm   ..\fig\fig4-15.doc
copy strcpy.asm   ..\fig\fig4-16.doc
copy strupr.asm   ..\fig\fig4-17.doc
copy strlwr.asm   ..\fig\fig4-18.doc
copy strcmp.asm   ..\fig\fig4-19.doc
copy strncmp.asm  ..\fig\fig4-20.doc
copy strswap.asm  ..\fig\fig4-21.doc
copy memncpy.asm  ..\fig\fig4-22.doc
copy strins.asm   ..\fig\fig4-23.doc
copy strsrch.asm  ..\fig\fig4-24.doc
copy strcat.asm   ..\fig\fig4-25.doc
copy itoa.asm     ..\fig\fig4-26.doc
copy itoh.asm     ..\fig\fig4-27.doc
copy ltoa.asm     ..\fig\fig4-28.doc

copy prog5-1.asm  ..\fig\fig5-1.doc
copy errmsg.asm   ..\fig\fig5-2.doc
copy free.asm     ..\fig\fig5-3.doc
copy malloc.asm   ..\fig\fig5-4.doc
copy vdbox.asm    ..\fig\fig5-5.doc
copy initw.asm    ..\fig\fig5-6.doc
copy destw.asm    ..\fig\fig5-7.doc
copy dispw.asm    ..\fig\fig5-8.doc
copy remvw.asm    ..\fig\fig5-9.doc
copy wvdwrite.asm ..\fig\fig5-10.doc
copy wvdattr.asm  ..\fig\fig5-11.doc
copy wvdchar.asm  ..\fig\fig5-12.doc

copy prog6-1.asm  ..\fig\fig6-1.doc
copy msinit.asm   ..\fig\fig6-2.doc
copy mson.asm     ..\fig\fig6-3.doc
copy msoff.asm    ..\fig\fig6-4.doc
copy msstat.asm   ..\fig\fig6-5.doc
copy kbstat.asm   ..\fig\fig6-6.doc
copy kbread.asm   ..\fig\fig6-7.doc

copy prog7-1.asm  ..\fig\fig7-1.doc
copy prog7-2.asm  ..\fig\fig7-2.doc
copy initddw.asm  ..\fig\fig7-3.doc
copy dispddw.asm  ..\fig\fig7-4.doc
copy remvddw.asm  ..\fig\fig7-5.doc
copy destddw.asm  ..\fig\fig7-6.doc
copy initmb.asm   ..\fig\fig7-7.doc
copy dispmb.asm   ..\fig\fig7-8.doc

copy prog8-1.asm  ..\fig\fig8-1.doc
copy prog8-2.asm  ..\fig\fig8-2.doc
copy scan.inc     ..\fig\fig8-3.doc







